# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AIKaiwa' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIKaiwa
  pod 'SCLAlertView'
  pod 'Alamofire'
  pod "SlackTextViewController"
  pod 'RealmSwift'
  pod 'Alamofire-Synchronous', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'

  target 'AIKaiwaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AIKaiwaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
